//! Build script — compile CUDA kernels to PTX via nvcc.
//!
//! Detects CUDA_PATH, compiles kernels/*.cu → PTX, generates src/cuda/ptx.rs
//! with embedded PTX strings. Feature-gated: only runs with `--features cuda`.

#[cfg(feature = "cuda")]
use std::env;
#[cfg(feature = "cuda")]
use std::path::{Path, PathBuf};

fn main() {
    // Only compile CUDA kernels when the cuda feature is enabled
    #[cfg(feature = "cuda")]
    compile_cuda_kernels();

    // Always rerun if kernels change
    println!("cargo:rerun-if-changed=kernels/");
    println!("cargo:rerun-if-changed=build.rs");
}

#[cfg(feature = "cuda")]
fn compile_cuda_kernels() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let kernels_dir = Path::new("kernels");

    // Find nvcc
    let cuda_path = env::var("CUDA_PATH")
        .or_else(|_| env::var("CUDA_HOME"))
        .unwrap_or_else(|_| {
            if cfg!(windows) {
                "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v13.2".to_string()
            } else {
                "/usr/local/cuda".to_string()
            }
        });

    let nvcc = if cfg!(windows) {
        PathBuf::from(&cuda_path).join("bin").join("nvcc.exe")
    } else {
        PathBuf::from(&cuda_path).join("bin").join("nvcc")
    };

    if !nvcc.exists() {
        eprintln!("WARNING: nvcc not found at {:?}, CUDA kernels will not be compiled", nvcc);
        eprintln!("  Set CUDA_PATH or CUDA_HOME environment variable");
        generate_empty_ptx_module(&out_dir);
        return;
    }

    eprintln!("Found nvcc at {:?}", nvcc);

    // Collect .cu files
    let cu_files: Vec<PathBuf> = std::fs::read_dir(kernels_dir)
        .expect("kernels/ directory not found")
        .filter_map(|entry| {
            let entry = entry.ok()?;
            let path = entry.path();
            if path.extension()?.to_str()? == "cu" {
                Some(path)
            } else {
                None
            }
        })
        .collect();

    if cu_files.is_empty() {
        eprintln!("WARNING: No .cu files found in kernels/");
        generate_empty_ptx_module(&out_dir);
        return;
    }

    // Compile each .cu → .ptx
    let mut ptx_entries = Vec::new();

    for cu_file in &cu_files {
        let stem = cu_file.file_stem().unwrap().to_str().unwrap();
        let ptx_path = out_dir.join(format!("{}.ptx", stem));

        eprintln!("Compiling {:?} → {:?}", cu_file, ptx_path);

        // Find MSVC cl.exe for nvcc host compilation (Windows)
        let mut cmd = std::process::Command::new(&nvcc);
        cmd.args(&[
                "--ptx",
                "-arch=sm_86",              // RTX 3080 (Ampere)
                "-O3",
                "--use_fast_math",
                "-I", kernels_dir.to_str().unwrap(),
                "-o", ptx_path.to_str().unwrap(),
                cu_file.to_str().unwrap(),
            ]);

        // On Windows, point nvcc to cl.exe if not in PATH
        if cfg!(windows) {
            let msvc_paths = [
                r"C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\VC\Tools\MSVC\14.50.35717\bin\Hostx64\x64",
                r"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64",
            ];
            for p in &msvc_paths {
                let cl = Path::new(p).join("cl.exe");
                if cl.exists() {
                    cmd.arg("-ccbin").arg(p);
                    break;
                }
            }
        }

        let status = cmd.status();

        match status {
            Ok(s) if s.success() => {
                ptx_entries.push((stem.to_string(), ptx_path));
            }
            Ok(s) => {
                eprintln!("WARNING: nvcc failed for {} (exit code {:?})", stem, s.code());
            }
            Err(e) => {
                eprintln!("WARNING: Failed to run nvcc for {}: {}", stem, e);
            }
        }
    }

    // Generate src/cuda/ptx.rs with include_str! for each compiled PTX
    generate_ptx_module(&out_dir, &ptx_entries);
}

#[cfg(feature = "cuda")]
fn generate_ptx_module(out_dir: &Path, entries: &[(String, PathBuf)]) {
    let mut code = String::from(
        "// Auto-generated PTX module — do not edit manually.\n\
         // Generated by build.rs from kernels/*.cu\n\n"
    );

    for (name, ptx_path) in entries {
        let const_name = name.to_uppercase();
        code.push_str(&format!(
            "pub const PTX_{}: &str = include_str!(\"{}\");\n",
            const_name,
            ptx_path.to_str().unwrap().replace('\\', "/"),
        ));
    }

    // Write to OUT_DIR (included via include! in kernels.rs)
    let ptx_rs = out_dir.join("ptx_generated.rs");
    std::fs::write(&ptx_rs, code).expect("Failed to write ptx_generated.rs");
    eprintln!("Generated {:?} with {} kernel(s)", ptx_rs, entries.len());
}

#[allow(dead_code)]
fn generate_empty_ptx_module(out_dir: &Path) {
    let code = "// No CUDA kernels compiled (nvcc not found or cuda feature disabled).\n";
    let ptx_rs = out_dir.join("ptx_generated.rs");
    std::fs::write(&ptx_rs, code).expect("Failed to write empty ptx_generated.rs");
}
